name: Bug Report
description: Report a bug or unexpected behavior
title: "[BUG]: "
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: A clear description of the bug
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. 
        2. 
        3. 
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      placeholder: |
        - OS: 
        - Ruby: 
        - Browser (if relevant): 

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Logs, screenshots, error messages, etc.
