name: Chore
description: Small cleanup, maintenance, or housekeeping tasks
title: "[CHORE]: "
labels: ["chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: What needs to be cleaned up?
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Done when
      placeholder: |
        - [ ] 
        - [ ] 
    validations:
      required: true
