name: DevOps / Infrastructure
description: CI/CD, deployment, tooling, and infrastructure tasks
title: "[DEVOPS]: "
labels: ["devops"]
body:
  - type: textarea
    id: description
    attributes:
      label: What needs to be done?
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - CI/CD
        - Deployment
        - Docker / Containers
        - Database
        - Monitoring
        - Repo setup
        - Other
    validations:
      required: true

  - type: textarea
    id: done
    attributes:
      label: Done when
      placeholder: |
        - [ ] 
        - [ ] 
        - [ ] 
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
