AllCops:
  TargetRubyVersion: 3.2.3 # Matches our runtime Ruby version
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Style/Documentation:
  Enabled: false

# To be deleted when we have all endpoints implemented
Style/EmptyMethod:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false