AllCops:
  TargetRubyVersion: 3.2.3 # Matches our runtime Ruby version
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 200

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Code complexity, a bit high but pragmatical
Metrics/AbcSize:
  Max: 30

Style/Documentation:
  Enabled: false

# To be deleted when we have all endpoints implemented
Style/EmptyMethod:
  Enabled: false

# Enables empty boxes
# TODO delete when we have all endpoints implemented
Lint/EmptyBlock:
  Enabled: false

# No class instance variable required
# since we have no subclasses
Style/ClassVars:
  Enabled: false

