# frozen_string_literal: true

source "https://rubygems.org"

gem "sinatra", "~> 3.0"
gem "sinatra-activerecord"
gem "activerecord", "~> 7.0"
gem "sqlite3", "~> 1.6"
gem "ostruct" # We avoid this warning: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems starting from Ruby 4.0.0.
gem "rackup"
gem "puma"
gem "dotenv"